### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by stomaskov** [Fridus/webpack-watch-files-plugin#4]
Used version 1.0.1.

(node:439) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at WebpackWatchPlugin.apply (/project_path/node_modules/webpack-watch-files-plugin/lib/index.js:54:16)
    at webpack (/project_path/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/project_path/node_modules/webpack-cli/bin/webpack.js:436:16)
    at yargs.parse (/project_path/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Object.parse (/project_path/node_modules/yargs/yargs.js:552:18)
    at /project_path/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/project_path/node_modules/webpack-cli/bin/webpack.js:514:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/project_path/node_modules/webpack/bin/webpack.js:80:2)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Hash: f52528cc876a73b84f5a
Version: webpack 4.5.0

**Comment by Fridus** [comment]
Hi ! This is fixed in version 1.0.2 ;)
